add CD prod stage

diff --git a/.bluemix/cd.pipeline.yml b/.bluemix/cd.pipeline.yml
--- a/.bluemix/cd.pipeline.yml
+++ b/.bluemix/cd.pipeline.yml
@@ -141,3 +141,82 @@ stages:
       fi
     enable_tests: true
     test_file_pattern: '*.xml'
+- name: PROD
+  inputs:
+  - type: job
+    stage: BUILD
+    job: Build umbrella chart
+  triggers:
+  - type: stage
+  properties:
+  - name: buildprops
+    value: build.properties
+    type: file
+  - name: CLUSTER_NAMESPACE
+    value: ${PROD_CLUSTER_NAMESPACE}
+    type: text
+  - name: CF_APP_NAME
+    value: undefined
+    type: text
+  - name: APP_URL
+    value: undefined
+    type: text
+  - name: LOGICAL_ENV_NAME
+    value: PROD
+    type: text
+  - name: SERVICE_ID
+    value: undefined
+    type: text
+  jobs:
+  - name: Production gate
+    type: tester
+    script: |-
+      #!/bin/bash
+      #set -x
+      source <(curl -sSL "https://raw.githubusercontent.com/open-toolchain/commons/master/scripts/check_umbrella_gate.sh")
+  - name: Config service
+    type: deployer
+    target:
+      region_id: ${PROD_REGION_ID}
+      organization: ${PROD_ORG_NAME}
+      space: ${PROD_SPACE_NAME}
+      application: ${CF_APP_NAME}
+    script: |
+      #!/bin/bash
+      SERVICE=$(cf services | grep myMicroservicesCloudant ||:)
+      if [ ! -z "$SERVICE" ]; then
+        PLAN=$(echo $SERVICE | awk '{print $3}')
+        if [ $PLAN == "Shared" ]; then
+          echo "Attempting to delete deprecated service (myMicroservicesCloudant:$PLAN)."
+          echo "Note: This can fail if the service is still bound to apps or service keys."
+          echo "      If so, please delete these apps or service keys explicitly first."
+          cf delete-service myMicroservicesCloudant -f
+          cf create-service cloudantNoSQLDB Lite myMicroservicesCloudant
+        else
+          echo "Keeping existing service (myMicroservicesCloudant:$PLAN)."
+        fi
+      else
+        cf create-service cloudantNoSQLDB Lite myMicroservicesCloudant
+      fi
+      export SERVICE_ID=$( cf service myMicroservicesCloudant --guid | tail -n 1)
+  - name: Config cluster
+    type: deployer
+    target:
+      region_id: ${PROD_REGION_ID}
+      api_key: ${API_KEY}
+      kubernetes_cluster: ${PROD_CLUSTER_NAME}
+    script: |
+      #!/bin/bash
+      #set -x
+      source <(curl -sSL "https://raw.githubusercontent.com/open-toolchain/commons/master/scripts/check_predeploy.sh")
+      source <(curl -sSL "https://raw.githubusercontent.com/open-toolchain/commons/master/scripts/cluster_bind_service.sh")
+  - name: Deploy umbrella chart
+    type: deployer
+    target:
+      region_id: ${PROD_REGION_ID}
+      api_key: ${API_KEY}
+      kubernetes_cluster: ${PROD_CLUSTER_NAME}
+    script: |
+      #!/bin/bash
+      #set -x
+      source <(curl -sSL "https://raw.githubusercontent.com/open-toolchain/commons/master/scripts/deploy_umbrella_chart.sh")
