Revert "Remove CF Org & Space need and use RG service for cluster binding (#37)"
This reverts commit d27d57caeb25cc3496c1fa4f73b099199eb97bdf.

diff --git a/.bluemix/cd.pipeline.yml b/.bluemix/cd.pipeline.yml
--- a/.bluemix/cd.pipeline.yml
+++ b/.bluemix/cd.pipeline.yml
@@ -24,7 +24,7 @@ stages:
       region_id: ${REGISTRY_REGION_ID}
       api_key: ${API_KEY}
     namespace: ${REGISTRY_NAMESPACE}
-    image_name: ${APP_NAME}
+    image_name: ${CF_APP_NAME}
     script: |
       #!/bin/bash
       #set -x
@@ -51,6 +51,12 @@ stages:
   - name: APP_URL
     value: undefined
     type: text
+  - name: SAUCE_USERNAME
+    value: {{services.test.parameters.username}}
+    type: text
+  - name: SAUCE_ACCESS_KEY
+    value: {{services.test.parameters.key}}
+    type: text
   - name: LOGICAL_ENV_NAME
     value: STAGING
     type: text
@@ -73,6 +79,32 @@ stages:
       #!/bin/bash
       #set -x
       source <(curl -sSL "https://raw.githubusercontent.com/open-toolchain/commons/master/scripts/check_umbrella_gate.sh")
+  - name: Config service
+    type: deployer
+    target:
+      region_id: ${STAGING_REGION_ID}
+      organization: ${STAGING_ORG_NAME}
+      space: ${STAGING_SPACE_NAME}
+      application: ${CF_APP_NAME}
+      api_key: ${API_KEY}
+    script: |
+      #!/bin/bash
+      SERVICE=$(cf services | grep myMicroservicesCloudant ||:)
+      if [ ! -z "$SERVICE" ]; then
+        PLAN=$(echo $SERVICE | awk '{print $3}')
+        if [ $PLAN == "Shared" ]; then
+          echo "Attempting to delete deprecated service (myMicroservicesCloudant:$PLAN)."
+          echo "Note: This can fail if the service is still bound to apps or service keys."
+          echo "      If so, please delete these apps or service keys explicitly first."
+          cf delete-service myMicroservicesCloudant -f
+          cf create-service cloudantNoSQLDB Lite myMicroservicesCloudant
+        else
+          echo "Keeping existing service (myMicroservicesCloudant:$PLAN)."
+        fi
+      else
+        cf create-service cloudantNoSQLDB Lite myMicroservicesCloudant
+      fi
+      export SERVICE_ID=$( cf service myMicroservicesCloudant --guid | tail -n 1)
   - name: Config cluster
     type: deployer
     target:
@@ -83,19 +115,7 @@ stages:
       #!/bin/bash
       #set -x
       source <(curl -sSL "https://raw.githubusercontent.com/open-toolchain/commons/master/scripts/check_predeploy_helm.sh")
-  - name: Config service
-    type: deployer
-    target:
-      api_key: ${API_KEY}
-      region_id: ${STAGING_REGION_ID}
-      resource_group: ${STAGING_RESOURCE_GROUP}
-      kubernetes_cluster: ${STAGING_CLUSTER_NAME}
-    script: |
-      #!/bin/bash
-      INSTANCE_NAME=myMicroservicesCloudant
-      SERVICE_NAME=cloudantnosqldb
-      SERVICE_PLAN=lite
-      source <(curl -sSL "https://raw.githubusercontent.com/open-toolchain/commons/master/scripts/cluster_config_service.sh")      
+      source <(curl -sSL "https://raw.githubusercontent.com/open-toolchain/commons/master/scripts/cluster_bind_service.sh")
   - name: Deploy umbrella chart
     type: deployer
     target:
@@ -111,6 +131,10 @@ stages:
     extension_id: ibm.devops.services.pipeline.saucelabs
     services:
       - ${SAUCE_LABS}
+    target:
+      region_id: ${STAGING_REGION_ID}
+      organization: ${STAGING_ORG_NAME}
+      space: ${STAGING_SPACE_NAME}
     DL_ASSETS: 'false'
     SELECT_CMD: custom
     COMMAND: |-
@@ -159,6 +183,32 @@ stages:
       #!/bin/bash
       #set -x
       source <(curl -sSL "https://raw.githubusercontent.com/open-toolchain/commons/master/scripts/check_umbrella_gate.sh")
+  - name: Config service
+    type: deployer
+    target:
+      region_id: ${PROD_REGION_ID}
+      organization: ${PROD_ORG_NAME}
+      space: ${PROD_SPACE_NAME}
+      application: ${CF_APP_NAME}
+      api_key: ${API_KEY}
+    script: |
+      #!/bin/bash
+      SERVICE=$(cf services | grep myMicroservicesCloudant ||:)
+      if [ ! -z "$SERVICE" ]; then
+        PLAN=$(echo $SERVICE | awk '{print $3}')
+        if [ $PLAN == "Shared" ]; then
+          echo "Attempting to delete deprecated service (myMicroservicesCloudant:$PLAN)."
+          echo "Note: This can fail if the service is still bound to apps or service keys."
+          echo "      If so, please delete these apps or service keys explicitly first."
+          cf delete-service myMicroservicesCloudant -f
+          cf create-service cloudantNoSQLDB Lite myMicroservicesCloudant
+        else
+          echo "Keeping existing service (myMicroservicesCloudant:$PLAN)."
+        fi
+      else
+        cf create-service cloudantNoSQLDB Lite myMicroservicesCloudant
+      fi
+      export SERVICE_ID=$( cf service myMicroservicesCloudant --guid | tail -n 1)
   - name: Config cluster
     type: deployer
     target:
@@ -169,19 +219,7 @@ stages:
       #!/bin/bash
       #set -x
       source <(curl -sSL "https://raw.githubusercontent.com/open-toolchain/commons/master/scripts/check_predeploy_helm.sh")
-  - name: Config service
-    type: deployer
-    target:
-      api_key: ${API_KEY}
-      region_id: ${PROD_REGION_ID}
-      resource_group: ${PROD_RESOURCE_GROUP}
-      kubernetes_cluster: ${PROD_CLUSTER_NAME}
-    script: |
-      #!/bin/bash
-      INSTANCE_NAME=myMicroservicesCloudant
-      SERVICE_NAME=cloudantnosqldb
-      SERVICE_PLAN=lite
-      source <(curl -sSL "https://raw.githubusercontent.com/open-toolchain/commons/master/scripts/cluster_config_service.sh")
+      source <(curl -sSL "https://raw.githubusercontent.com/open-toolchain/commons/master/scripts/cluster_bind_service.sh")
   - name: Deploy umbrella chart
     type: deployer
     target:
